GITEA_VERSION=1.22.1
GITEA_DOWNLOADBASEURL=https://dl.gitea.com/gitea
GITEA_BINFILENAME="gitea-${GITEA_VERSION}-${OS}-${ARCH}"
GITEA_DOWNLOADURL="${GITEA_DOWNLOADBASEURL}/${GITEA_VERSION}/${GITEA_BINFILENAME}"
GITEA_BINARY=${DLDIR}/${GITEA_BINFILENAME}
GITEA_BINARY_CHECKSUMFILE=${DLDIR}/${GITEA_BINFILENAME}.asc
GITEA_GPGKEYID=7C9E68152594688862D62AF62D9AE806EC1592E2
GITEA_GPGKEYSERVER=keys.openpgp.org
