GITEA_VERSION=1.22.1
GITEA_DOWNLOADBASEURL=https://dl.gitea.com/gitea
GITEA_BINFILE_NAME="gitea-${GITEA_VERSION}-${OS}-${ARCH}"
GITEA_BINFILE_LOCAL=${DLDIR}/${GITEA_BINFILE_NAME}
GITEA_DOWNLOADURL="${GITEA_DOWNLOADBASEURL}/${GITEA_VERSION}/${GITEA_BINFILE_NAME}"
GITEA_BINFILE_CHKSUMFILE=${DLDIR}/${GITEA_BINFILE_NAME}.asc
GITEA_GPGKEYID=7C9E68152594688862D62AF62D9AE806EC1592E2
GITEA_GPGKEYSERVER=keys.openpgp.org
